spring.application.name=spring-FW-practice
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.open-in-view=false
certificate.alias=${CERTIFICATE.ALIAS}
certificate.path=keystore.jks
certificate.password=${CERTIFICATE.PASSWORD}
spring.jackson.deserialization.fail-on-unknown-properties=true